name: MelooonCensor
main: io.github.jacobmarshall.meloooncensor.MelooonCensor
version: 3.0.2
author: Jacob Marshall <jacob@manage.net.nz>
commands:
  censor:
    description: Add/remove censored/ignored words from chat.
    aliases: [mcensor, meloooncensor]
    usage: "/censor add (censor|ignore) (word),remove (censor|ignore) (word), list (censor|ignore), (enable|disable)"