name: MelooonCensor-Reloaded
main: io.github.behoston.meloooncensor.MelooonCensor
version: 4.0.0
api-version: '1.15'
author: Behoston <mlegiecki@gmail.com>
commands:
  censor:
    description: Add/remove censored/ignored words from chat.
    aliases: [mcensor, meloooncensor]
    usage: "/censor add (censor|ignore) (word),remove (censor|ignore) (word), list (censor|ignore), (enable|disable), reload"